### PR TITLE
Adding inverted NED logo

### PR DESCRIPTION
**Pull request by alexwilson**

### CODE REVIEW

**Comment by alicebartlett** [comment]
Can you run that logo through a compression tool like SVGO (or you could use the online version: https://jakearchibald.github.io/svgomg/)

**Comment by alicebartlett** [comment]
Can you run that logo through a compression tool like SVGO (or you could use the online version: https://jakearchibald.github.io/svgomg/)

Otherwise though this looks fine :+1:

**Comment by alexwilson** [comment]
I've just done that, and also compressed the other "new" NED logo at the same time.

**Comment by notlee** [comment]
Nice, looks good 👍

**Pull request merged**
