### PR TITLE
Introduce BDP logo to deprecate NED.

### PR DESCRIPTION
**Pull request by alexwilson**

### CODE REVIEW

**Comment by alexwilson** [comment]
Instead of replacing the current logos, should add new ones for `board-director-programme` instead.

**Comment by notlee** [comment]
I'm [not sure if this is still true](https://github.com/financial-times/fticons#when-i-convert-my-icons-to-png-theyre-blurry) (will check tomorrow), but you might want to remove the height from ` src/board-director-programme.svg`

**Comment by alexwilson** [comment]
Ah good catch!

**Comment by notlee** [comment]
Ah [it](https://github.com/financial-times/fticons#when-i-convert-my-icons-to-png-theyre-blurry) does [appear to be telling the truth](https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo-v1%3Abrand-brexit?source=test&width=2000&height=2000&format=png&quality=lossless) still (that image has ` viewBox="0 0 272 272"` and looks pretty bad when scaled to 2000px and converted to png with "lossless" quality). I'd recommend scaling them in an svg editor to increase their viewbox size, so they can be scaled and converted to png without blurring.

**Review by notlee — APPROVED** [review]

**Pull request merged**
