### PR TITLE
Removed whitespace around NED svg logo

### PR DESCRIPTION
**Pull request by umarsheikh13**

### CODE REVIEW

**Comment by alexwilson** [comment]
Hey @alicebartlett, is this okay?

**Comment by alicebartlett** [comment]
Well... two points.

1. Normally, changes to padding around images constitute a breaking change, as they might result in broken layout for the consumers. Breaking changes mean a major version change. In this case though we can pragmatically ignore this rule because nobody is using this logo from the image service.

2. The other thing is that branding guidelines usually contain a required amount of whitespace around a logo, so it can be useful to help people get this right by including it in the actual logo. Is there a reason why you want to remove the whitespace?

**Comment by umarsheikh13** [comment]
Hi @alicebartlett. If you have a look at the logo, it has a significant amount of white space around it which is causing layout issues for us hence why we're removing it.

**Comment by alicebartlett** [comment]
Ah, you mean at the bottom?

**Comment by alexwilson** [comment]
Yeah - I suspect we were given the wrong logo originally.  Looking around at other Non-Execs resources, it seems as though there's no padding present.  (e.g. http://www.non-execs.com/visitor-home/)

**Comment by alicebartlett** [comment]
Great, thanks for clearing that up. Yes this is fine.

**Comment by alicebartlett** [comment]
I'll merge and release

**Comment by alexwilson** [comment]
Thanks for this, and sorry for for the hassle! 🙂

**Pull request merged**
